import React from "react";
import { useGlobalContext } from "../utils/context";

const Submenu = () => {
  const container = React.useRef();
  const {
    location,
    isShowSubmenu,
    page: { page, links },
  } = useGlobalContext();

  // setting up usestate ref
  const [columns, setColumns] = React.useState("col-2");
  React.useEffect(() => {
    setColumns("col-2");
    //setting up the location of the submenu
    const submenuNode = container.current;
    const { center, bottom } = location;
    submenuNode.style.left = `${center}px`;
    submenuNode.style.top = `${bottom}px`;
    //setting up the column of the submenu

    if (links.length === 3) {
      setColumns("col-3");
    }
    if (links.length > 3) {
      setColumns("col-4");
    }
  }, [location, links]);

  return page == "Features" ? (
    <aside
      className={`${isShowSubmenu ? "submenu show" : "submenu"}`}
      ref={container}
    >
      <div className="sub-page-title">
        {" "}
        <b>{page}</b>
      </div>

      <section className="feature-submenu">
        <article className="feature-article">
          <p>
            Thousands of AI-powered images Go beyond the limits of your
            imagination with high quality images generated by Artificial
            Intelligence.
          </p>
          <button className="feature-btn">Get Started</button>
        </article>

        <div className={`feature-center`}>
          {links.map((link, index) => {
            const { url, icon, label } = link;
            console.log(icon);

            return (
              <a key={index} href={url} className="feature-links">
                <div className="feature-item">
                  <img
                    src={Object.values(icon)}
                    alt=""
                    className="feature-image"
                  />
                  <span className="feature-title"> {label}</span>
                </div>
              </a>
            );
          })}
        </div>
      </section>
    </aside>
  ) : (
    <aside
      className={`${isShowSubmenu ? "submenu show" : "submenu"}`}
      ref={container}
    >
      <div className="sub-page-title">
        {" "}
        <b>{page}</b>
      </div>

      <div className={`submenu-center ${columns}`}>
        {links.map((link, index) => {
          const { url, icon, label } = link;

          return (
            <a key={index} href={url} className="submenu-links">
              {icon}
              {label}
            </a>
          );
        })}
      </div>
    </aside>
  );
};

export default Submenu;
